


// import React from 'react';
// import { Input, Space, Card } from 'antd';
// import plantImage1 from './assets/human.jpg';
// import plantImage2 from './assets/human.jpg';
// import humanImage from './assets/human.jpg';

// const { Search } = Input;
// const { Meta } = Card;

// const onSearch = (value) => console.log(value);

// const cardData = [
//   { image: plantImage1, title: 'Golobal Metabolomics', description: 'www.plant.com' },
//   { image: plantImage2, title: 'Plant', description: 'www.plant.com' },
//   { image: humanImage, title: 'Human', description: 'www.human.com' },
// ];

// const Home: React.FC = () => (
//   <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '20px' }}>
//     <Search
//       placeholder="input search text"
//       allowClear
//       enterButton="Search"
//       size="large"
//       onSearch={onSearch}
//       // set the width of the search bar to fixed length: 500 px
//       style={{ width: '80%' }}
//     />
//     <div style={{ display: 'flex', gap: '20px' }}>
//       {cardData.map((card, i) => (
//         <Card
//           key={i}
//           hoverable
//           style={{ width: '30%' }}
//           cover={<img alt={card.title} src={card.image} />}
//         >
//           <Meta title={card.title} description={card.description} />
//         </Card>
//       ))}
//     </div>
//   </div>
// );

// export default Home;



import React from 'react';
import { Input, Space, Card } from 'antd';
import { useNavigate } from 'react-router-dom';
import plantImage1 from './assets/cil.jpg';
import plantImage2 from './assets/human.jpg';
import humanImage from './assets/plant.png';

const { Search } = Input;
const { Meta } = Card;

const onSearch = (value) => console.log(value);

const Home: React.FC = () => {
  const navigate = useNavigate();

  const cardData = [
    { image: plantImage1, title: 'Deep Metabolomics', onClick: () => navigate('/About')},
    { image: plantImage2, title: 'MCIDxKEGG (Human)', onClick: () => navigate('/MCIDxKEGG') },
    { image: humanImage, title: 'MCIDxPlant', onClick: () => navigate('/MCIDxPlant') },
  ];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '20px' }}>
      <Search
        placeholder="Search by MCID, like C00002R06001"
        allowClear
        enterButton="Search"
        size="large"
        onSearch={onSearch}
        style={{ width: '80%' }}
      />
      <p style={{ fontSize: '16px', width: '80%' }}>
        <strong>MycompoundID 2.0</strong> is an evidence-based metabolome library for identification of compounds of interest based on accurate mass generated by mass spectrometry (MS). 
        </p>

      
        



      <div style={{ display: 'flex', gap: '1%', width: '80%' }}>
        {cardData.map((card, i) => (
          <Card
            key={i}
            hoverable
            style={{ width: '30%' }}
            cover={<img alt={card.title} src={card.image} onClick={card.onClick} />}
          >
            <Meta title={card.title} />
          </Card>
        ))}
      </div>
    </div>
  );
};

export default Home;
